# Generated by Django 3.2.9 on 2021-11-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Название',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Текст',
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=400, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='note',
            name='theme',
            field=models.CharField(max_length=400, verbose_name='Тема'),
        ),
    ]
