# Generated by Django 3.2.9 on 2022-01-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211121_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='parsing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='summ',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='text1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
