# Generated by Django 3.2.9 on 2022-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220116_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ner_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='parsing_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
